/**
 * PDF Export Utility for TeamHub Specifications
 * Generates PDF documents from specification blocks
 */

interface Block {
  id: string;
  type: string;
  content: any;
  order: number;
}

interface SpecData {
  title: string;
  project?: string;
  version?: string;
  author?: string;
  team?: string;
  createdAt?: string;
  blocks: Block[];
}

/**
 * Generate HTML content from specification blocks
 */
export function generateSpecHTML(spec: SpecData, language: 'en' | 'ru'): string {
  const t = {
    specification: language === 'en' ? 'Technical Specification' : 'Техническое задание',
    version: language === 'en' ? 'Version' : 'Версия',
    project: language === 'en' ? 'Project' : 'Проект',
    author: language === 'en' ? 'Author' : 'Автор',
    team: language === 'en' ? 'Team' : 'Команда',
    date: language === 'en' ? 'Date' : 'Дата',
    generatedBy: language === 'en' ? 'Generated by TeamHub' : 'Создано в TeamHub',
  };

  const styles = `
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica', 'Arial', sans-serif;
        line-height: 1.6;
        color: #1a1a1a;
        padding: 40px;
        max-width: 900px;
        margin: 0 auto;
      }
      .header {
        border-bottom: 3px solid #10b981;
        padding-bottom: 20px;
        margin-bottom: 30px;
      }
      .header h1 {
        font-size: 32px;
        color: #10b981;
        margin-bottom: 10px;
      }
      .metadata {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 10px;
        margin-top: 15px;
        font-size: 14px;
        color: #666;
      }
      .metadata-item {
        display: flex;
        gap: 5px;
      }
      .metadata-label {
        font-weight: 600;
      }
      .block {
        margin-bottom: 30px;
        page-break-inside: avoid;
      }
      .block h1, .block h2, .block h3 {
        color: #10b981;
        margin-bottom: 12px;
      }
      .block h1 { font-size: 28px; margin-top: 30px; }
      .block h2 { font-size: 24px; margin-top: 25px; }
      .block h3 { font-size: 20px; margin-top: 20px; }
      .block p {
        margin-bottom: 12px;
        color: #4a4a4a;
      }
      .block ul, .block ol {
        margin-left: 30px;
        margin-bottom: 12px;
      }
      .block li {
        margin-bottom: 8px;
        color: #4a4a4a;
      }
      .block table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
        font-size: 14px;
      }
      .block table th {
        background-color: #f3f4f6;
        padding: 12px;
        text-align: left;
        font-weight: 600;
        border: 1px solid #e5e7eb;
      }
      .block table td {
        padding: 10px 12px;
        border: 1px solid #e5e7eb;
      }
      .block table tr:nth-child(even) {
        background-color: #f9fafb;
      }
      .block img {
        max-width: 100%;
        height: auto;
        border-radius: 8px;
        margin: 15px 0;
        box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      }
      .block pre {
        background-color: #1e293b;
        color: #e2e8f0;
        padding: 16px;
        border-radius: 8px;
        overflow-x: auto;
        font-size: 13px;
        line-height: 1.5;
        margin-bottom: 15px;
      }
      .block code {
        font-family: 'Courier New', Courier, monospace;
      }
      .block .link {
        color: #10b981;
        text-decoration: none;
        display: inline-flex;
        align-items: center;
        gap: 5px;
        padding: 8px 12px;
        border: 1px solid #10b981;
        border-radius: 6px;
        margin: 10px 0;
        transition: background-color 0.2s;
      }
      .block .link:hover {
        background-color: #ecfdf5;
      }
      .checklist {
        list-style: none;
        margin-left: 0;
      }
      .checklist-item {
        display: flex;
        align-items: flex-start;
        gap: 10px;
        margin-bottom: 10px;
        padding: 8px;
        border-radius: 4px;
        background-color: #f9fafb;
      }
      .checklist-item input[type="checkbox"] {
        margin-top: 4px;
        width: 18px;
        height: 18px;
      }
      .checklist-item.checked {
        background-color: #ecfdf5;
      }
      .checklist-item.checked .checklist-text {
        color: #10b981;
        text-decoration: line-through;
      }
      .footer {
        margin-top: 50px;
        padding-top: 20px;
        border-top: 1px solid #e5e7eb;
        text-align: center;
        font-size: 12px;
        color: #9ca3af;
      }
      @media print {
        body { padding: 20px; }
        .block { page-break-inside: avoid; }
      }
    </style>
  `;

  const header = `
    <div class="header">
      <h1>${spec.title}</h1>
      <div class="metadata">
        ${spec.version ? `<div class="metadata-item"><span class="metadata-label">${t.version}:</span><span>${spec.version}</span></div>` : ''}
        ${spec.project ? `<div class="metadata-item"><span class="metadata-label">${t.project}:</span><span>${spec.project}</span></div>` : ''}
        ${spec.author ? `<div class="metadata-item"><span class="metadata-label">${t.author}:</span><span>${spec.author}</span></div>` : ''}
        ${spec.team ? `<div class="metadata-item"><span class="metadata-label">${t.team}:</span><span>${spec.team}</span></div>` : ''}
        ${spec.createdAt ? `<div class="metadata-item"><span class="metadata-label">${t.date}:</span><span>${spec.createdAt}</span></div>` : ''}
      </div>
    </div>
  `;

  const blockHTML = spec.blocks
    .sort((a, b) => a.order - b.order)
    .map(block => renderBlock(block))
    .join('\n');

  const footer = `
    <div class="footer">
      <p>${t.generatedBy} - Avis Ecosystem</p>
    </div>
  `;

  return `
    <!DOCTYPE html>
    <html lang="${language}">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${spec.title}</title>
      ${styles}
    </head>
    <body>
      ${header}
      ${blockHTML}
      ${footer}
    </body>
    </html>
  `;
}

/**
 * Render individual block to HTML
 */
function renderBlock(block: Block): string {
  switch (block.type) {
    case 'heading':
      const level = block.content.level || 2;
      return `<div class="block"><h${level}>${escapeHTML(block.content.text)}</h${level}></div>`;

    case 'text':
      return `<div class="block"><p>${escapeHTML(block.content.text).replace(/\n/g, '<br>')}</p></div>`;

    case 'list':
      const listTag = block.content.ordered ? 'ol' : 'ul';
      const items = block.content.items.map((item: string) => `<li>${escapeHTML(item)}</li>`).join('\n');
      return `<div class="block"><${listTag}>${items}</${listTag}></div>`;

    case 'table':
      const headers = block.content.headers.map((h: string) => `<th>${escapeHTML(h)}</th>`).join('');
      const rows = block.content.rows
        .map((row: string[]) => {
          const cells = row.map((cell: string) => `<td>${escapeHTML(cell)}</td>`).join('');
          return `<tr>${cells}</tr>`;
        })
        .join('\n');
      return `
        <div class="block">
          <table>
            <thead><tr>${headers}</tr></thead>
            <tbody>${rows}</tbody>
          </table>
        </div>
      `;

    case 'image':
      return `
        <div class="block">
          <img src="${escapeHTML(block.content.url)}" alt="${escapeHTML(block.content.alt)}" />
        </div>
      `;

    case 'code':
      return `
        <div class="block">
          <pre><code>${escapeHTML(block.content.code)}</code></pre>
        </div>
      `;

    case 'link':
      return `
        <div class="block">
          <a href="${escapeHTML(block.content.url)}" class="link" target="_blank">
            🔗 ${escapeHTML(block.content.text)}
          </a>
        </div>
      `;

    case 'checklist':
      const checklistItems = block.content.items
        .map((item: any) => {
          const checked = item.checked ? 'checked' : '';
          const checkedClass = item.checked ? 'checked' : '';
          return `
            <div class="checklist-item ${checkedClass}">
              <input type="checkbox" ${checked} disabled />
              <span class="checklist-text">${escapeHTML(item.text)}</span>
            </div>
          `;
        })
        .join('\n');
      return `<div class="block"><div class="checklist">${checklistItems}</div></div>`;

    default:
      return '';
  }
}

/**
 * Escape HTML special characters
 */
function escapeHTML(str: string): string {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Export specification as PDF (opens in new window for printing/saving)
 */
export function exportSpecToPDF(spec: SpecData, language: 'en' | 'ru' = 'en'): void {
  const html = generateSpecHTML(spec, language);
  
  // Open in new window
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    
    // Wait for content to load, then trigger print dialog
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
      }, 250);
    };
  }
}

/**
 * Download specification as HTML file
 */
export function downloadSpecAsHTML(spec: SpecData, language: 'en' | 'ru' = 'en'): void {
  const html = generateSpecHTML(spec, language);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${spec.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
